#!/usr/bin/env bash
# Verifica qué sitios estábamos usando y fueron afectados por cloudbleed
# 
# © 2017 fauno <fauno@endefensadelsl.org>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.


url="https://raw.githubusercontent.com/pirate/sites-using-cloudflare/master/sorted_unique_cf.txt"
tmp_dir="$(mktemp -d /tmp/fuckflare.XXXX)"
dest_file="${fuckflare:-${tmp_dir}/fuckflare.txt}"


function download () {
	wget "${url}" -nc -O "${dest_file}"
}

function all_storage () {
  ls -1 ~/.mozilla/firefox/*/${1}
}

function any () {
  all_storage places.sqlite | while read -r i; do
		echo 'select url from moz_places;' | sqlite3 "$i"
	done \
	| cut -d/ -f3 \
	| sort -u
}

function cookies () {
  all_storage cookies.sqlite | while read -r i; do
		echo 'select baseDomain from moz_cookies;' | sqlite3 "$i"
	done \
	| cut -d/ -f3 \
	| sort -u
}

function logins () {
  all_storage logins.json \
  | xargs -d "\n" cat \
  | grep -o "https\?://[^\"]\+" \
  | cut -d/ -f3 \
  | cut -d: -f1 \
  | sort -u
}

function compare () {
  local _compare_file="${tmp_dir}/compare.$1"

	comm -12 <($1) <(sort "${dest_file}") | tee "${_compare_file}"
  wc -l < "${_compare_file}"
}

download
compare ${1:-any}
